class Limit:
    """Настройка констант моделей"""

    CHAR_LIMIT_TAG_NAME = 32
    CHAR_LIMIT_TAG_SLUG_NAME = 32
    CHAR_LIMIT_TAG_HEX_COLOR = 7

    CHAR_LIMIT_INGREDIENT_NAME = 128
    CHAR_LIMIT_INGREDIENT_MEASUREMENT_UNIT = 32

    CHAR_LIMIT_RECIPE_TITLE = 255
    MIN_VALUE_RECIPE_TIME_COOKING = 1

    MIN_VALUE_RECIPEINGREDIENT_AMOUNT = 1

    CHAR_LIMIT_USER_USERNAME = 150
    CHAR_LIMIT_USER_EMAIL = 254
    CHAR_LIMIT_USER_FIRST_NAME = 150
    CHAR_LIMIT_USER_LAST_NAME = 150
    CHAR_LIMIT_USER_PASSWORD = 150
