"""Настройка констант User"""

# Модель User
CHAR_LIMIT_USER_USERNAME = 150
CHAR_LIMIT_USER_EMAIL = 254
CHAR_LIMIT_USER_FIRST_NAME = 150
CHAR_LIMIT_USER_LAST_NAME = 150
CHAR_LIMIT_USER_PASSWORD = 150

VISUAL_CHAR = 32

# Пагинация
PAGINATION_PAGE_SIZE = 6
