# Generated by Django 4.2.10 on 2024-03-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_alter_favorite_options_alter_ingredient_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Название"),
        ),
    ]
