# Generated by Django 4.2.10 on 2024-03-10 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_alter_ingredient_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                help_text="Пример: #A7F300",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        code="Invalide color",
                        message="Цвет надо указывать в HEX формате",
                        regex="^#[A-Fa-f0-9]{6}$",
                    )
                ],
                verbose_name="Цвет в HEX",
            ),
        ),
    ]
