# Generated by Django 4.2.10 on 2024-03-10 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="Invalide username",
                        message="Можно использовать буквы латинского алфавита, цифры и символы: '.', '@', '_', '-', '+'.",
                        regex="^[\\w.@+-]+\\Z",
                    )
                ],
                verbose_name="Имя пользователя",
            ),
        ),
    ]
